-- WolloShare PostgreSQL schema for Supabase
-- Converted from database/schema.sql and the project migrations.
-- Run this file in the Supabase SQL Editor.

-- ============================================================
-- Shared updated_at trigger
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

-- ============================================================
-- UNIVERSITIES
-- ============================================================
CREATE TABLE universities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    short_name VARCHAR(50) NOT NULL,
    email_domain VARCHAR(100) NOT NULL,
    address TEXT,
    logo_url VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_universities_active ON universities (is_active);
CREATE INDEX idx_universities_email_domain ON universities (email_domain);

-- ============================================================
-- FACULTIES / COLLEGES
-- ============================================================
CREATE TABLE faculties (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    short_name VARCHAR(50),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_faculties_university FOREIGN KEY (university_id)
        REFERENCES universities(id) ON DELETE CASCADE
);

CREATE INDEX idx_faculties_university ON faculties (university_id);
CREATE INDEX idx_faculties_active ON faculties (is_active);

-- ============================================================
-- DEPARTMENTS
-- ============================================================
CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_departments_faculty FOREIGN KEY (faculty_id)
        REFERENCES faculties(id) ON DELETE CASCADE
);

CREATE INDEX idx_departments_faculty ON departments (faculty_id);
CREATE INDEX idx_departments_active ON departments (is_active);
CREATE INDEX idx_departments_name ON departments (name);

-- ============================================================
-- ACADEMIC LEVELS
-- ============================================================
CREATE TABLE academic_levels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_freshman BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_levels_order ON academic_levels (display_order);
CREATE INDEX idx_levels_active ON academic_levels (is_active);

-- ============================================================
-- SEMESTERS
-- ============================================================
CREATE TABLE semesters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    short_name VARCHAR(20) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_semesters_active ON semesters (is_active);
CREATE INDEX idx_semesters_order ON semesters (display_order);

-- ============================================================
-- RESOURCE TYPES
-- ============================================================
CREATE TABLE resource_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    extension VARCHAR(100),
    icon VARCHAR(100),
    max_file_size BIGINT NOT NULL DEFAULT 52428800,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- USERS (Students & Admins)
-- ============================================================
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    student_id VARCHAR(50) UNIQUE,
    invitation_code VARCHAR(80),
    phone VARCHAR(20),
    profile_image VARCHAR(500),
    university_id_card VARCHAR(500),
    role VARCHAR(20) NOT NULL DEFAULT 'student',
    account_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    verification_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    rejection_reason TEXT,
    verified_by INTEGER,
    verified_at TIMESTAMP NULL,
    university_id INTEGER,
    faculty_id INTEGER,
    department_id INTEGER,
    academic_level_id INTEGER,
    semester_id INTEGER,
    refresh_token VARCHAR(500),
    last_login_at TIMESTAMP NULL,
    password_changed_at TIMESTAMP NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_role CHECK (role IN ('student', 'admin')),
    CONSTRAINT chk_users_account_status CHECK (account_status IN ('pending', 'active', 'suspended', 'disabled')),
    CONSTRAINT chk_users_verification_status CHECK (verification_status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT fk_users_university FOREIGN KEY (university_id)
        REFERENCES universities(id) ON DELETE SET NULL,
    CONSTRAINT fk_users_faculty FOREIGN KEY (faculty_id)
        REFERENCES faculties(id) ON DELETE SET NULL,
    CONSTRAINT fk_users_department FOREIGN KEY (department_id)
        REFERENCES departments(id) ON DELETE SET NULL,
    CONSTRAINT fk_users_academic_level FOREIGN KEY (academic_level_id)
        REFERENCES academic_levels(id) ON DELETE SET NULL,
    CONSTRAINT fk_users_semester FOREIGN KEY (semester_id)
        REFERENCES semesters(id) ON DELETE SET NULL,
    CONSTRAINT fk_users_verified_by FOREIGN KEY (verified_by)
        REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_student_id ON users (student_id);
CREATE INDEX idx_users_invitation_code ON users (invitation_code);
CREATE INDEX idx_users_role ON users (role);
CREATE INDEX idx_users_account_status ON users (account_status);
CREATE INDEX idx_users_verification_status ON users (verification_status);
CREATE INDEX idx_users_department ON users (department_id);
CREATE INDEX idx_users_academic_level ON users (academic_level_id);
CREATE INDEX idx_users_semester ON users (semester_id);
CREATE INDEX idx_users_active ON users (is_active);

-- ============================================================
-- STUDENT VERIFICATION LOG
-- ============================================================
CREATE TABLE student_verifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    admin_id INTEGER NOT NULL,
    action VARCHAR(20) NOT NULL,
    reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_student_verifications_action CHECK (action IN ('approved', 'rejected', 'suspended', 'reactivated')),
    CONSTRAINT fk_verifications_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_verifications_admin FOREIGN KEY (admin_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_verifications_user ON student_verifications (user_id);
CREATE INDEX idx_verifications_admin ON student_verifications (admin_id);
CREATE INDEX idx_verifications_action ON student_verifications (action);

-- ============================================================
-- COURSES
-- ============================================================
CREATE TABLE courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER,
    academic_level_id INTEGER NOT NULL,
    semester_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50),
    description TEXT,
    credit_hours DECIMAL(3,1),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_courses_department FOREIGN KEY (department_id)
        REFERENCES departments(id) ON DELETE SET NULL,
    CONSTRAINT fk_courses_level FOREIGN KEY (academic_level_id)
        REFERENCES academic_levels(id) ON DELETE CASCADE,
    CONSTRAINT fk_courses_semester FOREIGN KEY (semester_id)
        REFERENCES semesters(id) ON DELETE CASCADE
);

CREATE INDEX idx_courses_department ON courses (department_id);
CREATE INDEX idx_courses_level ON courses (academic_level_id);
CREATE INDEX idx_courses_semester ON courses (semester_id);
CREATE INDEX idx_courses_active ON courses (is_active);
CREATE INDEX idx_courses_name ON courses (name);

-- ============================================================
-- RESOURCES
-- ============================================================
CREATE TABLE resources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    course_id INTEGER,
    resource_type_id INTEGER,
    category VARCHAR(30) NOT NULL DEFAULT 'course_material',
    chapter VARCHAR(100),
    department_id INTEGER,
    academic_level_id INTEGER,
    semester_id INTEGER,
    file_name VARCHAR(500) NOT NULL,
    original_file_name VARCHAR(500) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    file_size BIGINT NOT NULL,
    mime_type VARCHAR(100),
    file_extension VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    rejection_reason TEXT,
    reviewed_by INTEGER,
    reviewed_at TIMESTAMP NULL,
    download_count INTEGER NOT NULL DEFAULT 0,
    view_count INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_resources_category CHECK (category IN ('course_material', 'assignment', 'past_exam')),
    CONSTRAINT chk_resources_status CHECK (status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT fk_resources_uploader FOREIGN KEY (uploader_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_resources_course FOREIGN KEY (course_id)
        REFERENCES courses(id) ON DELETE SET NULL,
    CONSTRAINT fk_resources_type FOREIGN KEY (resource_type_id)
        REFERENCES resource_types(id) ON DELETE SET NULL,
    CONSTRAINT fk_resources_department FOREIGN KEY (department_id)
        REFERENCES departments(id) ON DELETE SET NULL,
    CONSTRAINT fk_resources_level FOREIGN KEY (academic_level_id)
        REFERENCES academic_levels(id) ON DELETE SET NULL,
    CONSTRAINT fk_resources_semester FOREIGN KEY (semester_id)
        REFERENCES semesters(id) ON DELETE SET NULL,
    CONSTRAINT fk_resources_reviewer FOREIGN KEY (reviewed_by)
        REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_resources_uploader ON resources (uploader_id);
CREATE INDEX idx_resources_course ON resources (course_id);
CREATE INDEX idx_resources_department ON resources (department_id);
CREATE INDEX idx_resources_level ON resources (academic_level_id);
CREATE INDEX idx_resources_semester ON resources (semester_id);
CREATE INDEX idx_resources_category ON resources (category);
CREATE INDEX idx_resources_status ON resources (status);
CREATE INDEX idx_resources_active ON resources (is_active);
CREATE INDEX idx_resources_title ON resources (title);
CREATE INDEX idx_resources_created ON resources (created_at);
CREATE INDEX idx_resources_chapter ON resources (chapter);
CREATE INDEX idx_resources_search ON resources USING GIN (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, '')));

-- ============================================================
-- BOOKMARKS
-- ============================================================
CREATE TABLE bookmarks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    resource_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookmarks_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_bookmarks_resource FOREIGN KEY (resource_id)
        REFERENCES resources(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_resource UNIQUE (user_id, resource_id)
);

CREATE INDEX idx_bookmarks_user ON bookmarks (user_id);

-- ============================================================
-- DOWNLOADS
-- ============================================================
CREATE TABLE downloads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    resource_id INTEGER NOT NULL,
    downloaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_downloads_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_downloads_resource FOREIGN KEY (resource_id)
        REFERENCES resources(id) ON DELETE CASCADE
);

CREATE INDEX idx_downloads_user ON downloads (user_id);
CREATE INDEX idx_downloads_resource ON downloads (resource_id);
CREATE INDEX idx_downloads_date ON downloads (downloaded_at);

-- ============================================================
-- RATINGS & REVIEWS
-- ============================================================
CREATE TABLE ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    resource_id INTEGER NOT NULL,
    rating SMALLINT NOT NULL,
    review TEXT,
    is_edited BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ratings_rating CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT fk_ratings_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ratings_resource FOREIGN KEY (resource_id)
        REFERENCES resources(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_resource_rating UNIQUE (user_id, resource_id)
);

CREATE INDEX idx_ratings_resource ON ratings (resource_id);
CREATE INDEX idx_ratings_user ON ratings (user_id);

-- ============================================================
-- REPORTS
-- ============================================================
CREATE TABLE reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id INTEGER NOT NULL,
    resource_id INTEGER NOT NULL,
    reason VARCHAR(30) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    resolved_by INTEGER,
    resolved_at TIMESTAMP NULL,
    admin_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_reports_reason CHECK (reason IN ('spam', 'copyright', 'duplicate', 'low_quality', 'wrong_department', 'other')),
    CONSTRAINT chk_reports_status CHECK (status IN ('pending', 'resolved', 'dismissed')),
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_resource FOREIGN KEY (resource_id)
        REFERENCES resources(id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_resolved_by FOREIGN KEY (resolved_by)
        REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_reports_status ON reports (status);
CREATE INDEX idx_reports_resource ON reports (resource_id);
CREATE INDEX idx_reports_reporter ON reports (reporter_id);

-- ============================================================
-- NOTIFICATIONS
-- ============================================================
CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT,
    reference_type VARCHAR(50),
    reference_id INTEGER,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_notifications_type CHECK (type IN ('verification_approved', 'verification_rejected', 'resource_approved', 'resource_rejected', 'report_resolved', 'admin_announcement', 'new_resource', 'system')),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_user ON notifications (user_id);
CREATE INDEX idx_notifications_read ON notifications (user_id, is_read);
CREATE INDEX idx_notifications_type ON notifications (type);
CREATE INDEX idx_notifications_created ON notifications (created_at);

-- ============================================================
-- AUDIT LOGS
-- ============================================================
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER NOT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50),
    entity_id INTEGER,
    description TEXT,
    metadata JSONB,
    ip_address VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_admin FOREIGN KEY (admin_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_audit_admin ON audit_logs (admin_id);
CREATE INDEX idx_audit_action ON audit_logs (action);
CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_logs (created_at);

-- ============================================================
-- SYSTEM SETTINGS
-- ============================================================
CREATE TABLE system_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT,
    setting_group VARCHAR(50) DEFAULT 'general',
    description TEXT,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_settings_updated_by FOREIGN KEY (updated_by)
        REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_settings_key ON system_settings (setting_key);
CREATE INDEX idx_settings_group ON system_settings (setting_group);

-- ============================================================
-- PASSWORD RESET TOKENS
-- ============================================================
CREATE TABLE password_resets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_resets_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_resets_token ON password_resets (token);
CREATE INDEX idx_resets_user ON password_resets (user_id);
CREATE INDEX idx_resets_expires ON password_resets (expires_at);

-- ============================================================
-- INVITATION CODES
-- ============================================================
CREATE TABLE invitation_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    university_id INTEGER NOT NULL,
    faculty_id INTEGER NOT NULL,
    department_id INTEGER NOT NULL,
    academic_level_id INTEGER NOT NULL,
    semester_id INTEGER NOT NULL,
    created_by INTEGER NOT NULL,
    max_uses INTEGER NOT NULL DEFAULT 1,
    used_count INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMP NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invitation_codes_university FOREIGN KEY (university_id)
        REFERENCES universities(id) ON DELETE RESTRICT,
    CONSTRAINT fk_invitation_codes_faculty FOREIGN KEY (faculty_id)
        REFERENCES faculties(id) ON DELETE RESTRICT,
    CONSTRAINT fk_invitation_codes_department FOREIGN KEY (department_id)
        REFERENCES departments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_invitation_codes_level FOREIGN KEY (academic_level_id)
        REFERENCES academic_levels(id) ON DELETE RESTRICT,
    CONSTRAINT fk_invitation_codes_semester FOREIGN KEY (semester_id)
        REFERENCES semesters(id) ON DELETE RESTRICT,
    CONSTRAINT fk_invitation_codes_created_by FOREIGN KEY (created_by)
        REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_invitation_codes_max_uses CHECK (max_uses >= 1),
    CONSTRAINT chk_invitation_codes_used_count CHECK (used_count >= 0 AND used_count <= max_uses)
);

CREATE INDEX idx_invitation_codes_active ON invitation_codes (is_active);
CREATE INDEX idx_invitation_codes_expires ON invitation_codes (expires_at);

-- ============================================================
-- Preserve MySQL ON UPDATE CURRENT_TIMESTAMP behavior.
-- ============================================================
CREATE TRIGGER trg_universities_updated_at BEFORE UPDATE ON universities FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_faculties_updated_at BEFORE UPDATE ON faculties FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_departments_updated_at BEFORE UPDATE ON departments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_academic_levels_updated_at BEFORE UPDATE ON academic_levels FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_semesters_updated_at BEFORE UPDATE ON semesters FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_courses_updated_at BEFORE UPDATE ON courses FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_resources_updated_at BEFORE UPDATE ON resources FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_ratings_updated_at BEFORE UPDATE ON ratings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_reports_updated_at BEFORE UPDATE ON reports FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_system_settings_updated_at BEFORE UPDATE ON system_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
